---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:

    - name: Install Java (Amazon Corretto 11)
      yum:
        name: java-11-amazon-corretto
        state: present
      ignore_errors: yes

    - name: Install Python 3 on Host Machines
      action: yum pkg=python3 state=present
      ignore_errors: yes

    - name: Install httpd on Host Machines
      action: yum pkg=httpd state=present
      ignore_errors: yes

    - name: Enable and start httpd on Host Machines
      action: service name=httpd state=started enabled=yes
      ignore_errors: yes

    - name: Enable and start httpd on Host Machines
      action: service name=httpd state=stopped enabled=yes
      ignore_errors: yes

    - name: Enable and start httpd on Host Machines
      action: service name=httpd state=restarted enabled=yes
      ignore_errors: yes

    
    - name: Add MariaDB 10.5 YUM repository
      yum_repository:
        name: MariaDB
        description: MariaDB 10.5 YUM repo
        baseurl: http://yum.mariadb.org/10.5/amazon2-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
      ignore_errors: yes

    - name: Install MariaDB on Host Machines
      action: yum pkg=MariaDB-server state=present
      ignore_errors: yes

